# Cloudflare Pages configuration
name = "my-hidden-deals"
compatibility_date = "2024-01-01"

[site]
bucket = "."

# Optional: Custom headers
[[rules]]
type = "header"
path = "/*"
headers = { "X-Frame-Options" = "SAMEORIGIN", "X-Content-Type-Options" = "nosniff" }

